# Generated by Django 3.0 on 2021-05-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
