# Generated by Django 3.0 on 2021-06-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
